name: jsdoc

on:
  push:
    branches: ['feature2']
  pull_request:
    branches: ['feature2']
jobs:
  Linter:
    runs-on: ubuntu-latest
    steps:
      - name: install the jsdoc
        run: npm install jsdoc
      - name: run the jsdoc
        run: npm run jsdoc