name: jsdoc

on:
  push:
    branches: ['none']
  pull_request:
    branches: ['none']
jobs:
  Linter:
    runs-on: ubuntu-latest
    steps:
      - name: install the jsdoc
        run: npm install jsdoc
      - name: run the jsdoc
        run: npm run jsdoc