name: jsdoc

on:
  push:
    branches: ['feature2']
  pull_request:
    branches: ['feature2']
jobs:
  JSDoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: install the jsdoc
        run: npm install jsdoc
      - name: run the jsdoc
        run: ./node_modules/.bin/jsdoc . -d docs/jsdocs/