name: Linter

on:
  push:
    branches: ['feature2']
  pull_request:
    branches: ['feature2']
jobs:
  Linter:
    runs-on: ubuntu-latest
    steps:
      - name: install the linter
        run: npm install eslint
      - name: run the linter
        run: ./node_modules/.bin/eslint .