name: UnitTest

on:
  push:
    branches: ['feature2']
  pull_request:
    branches: ['feature2']
jobs:
  Linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install Testing Tools
        run: npm install
      - name: Run Test Suite
        run: npm test